### ISSUE TITLE
mac 上 rsync 版本问题

### ISSUE THREAD

**Issue by lotusnowshen** [psjay/LiveCode#4]
此项目要求 rsync >= 3.1.0，但是 mac 自带的是 2.6.9，而且无法删除

我们用 homebrew 安装了新版之后，直接通过 alias 来覆盖

在 bashrc 或者 zshrc 里面加入：

`alias rsync="/usr/local/Cellar/rsync/3.1.3_1/bin/rsync"`

路径大家根据自己的版本来配置即可

**Comment by caesarjuly** [comment]
不需要吧，brew 可以直接覆盖依赖
